import type { CommentRecord, Hashtag, NotificationRecord, ReelRecord, User } from './types';

/**
 * Placeholder content for the prototype. Videos are public test clips (not football) until
 * real uploads flow through the video pipeline; posters are seeded placeholder images.
 */

const poster = (seed: string) => `https://picsum.photos/seed/gamepulse-${seed}/540/960`;

export const CURRENT_USER_ID = 'u_me';

export const users: User[] = [
  {
    id: CURRENT_USER_ID,
    username: 'you',
    displayName: 'You',
    bio: 'Football fan. Building my first Moments on GamePulse.',
    country: 'Nigeria',
    countryFlag: '🇳🇬',
    favoriteClub: 'Kano Pillars',
    verified: false,
    fans: 12,
    supporting: 48,
  },
  {
    id: 'u_1',
    username: 'skillzone',
    displayName: 'Skill Zone',
    bio: 'Daily skills, nutmegs and street football. 🔥',
    country: 'Brazil',
    countryFlag: '🇧🇷',
    favoriteClub: 'Flamengo',
    verified: true,
    fans: 482_300,
    supporting: 210,
  },
  {
    id: 'u_2',
    username: 'naija_ballers',
    displayName: 'Naija Ballers',
    bio: 'Grassroots football across Nigeria. Tag us in your Moments.',
    country: 'Nigeria',
    countryFlag: '🇳🇬',
    favoriteClub: 'Enyimba',
    verified: true,
    fans: 91_450,
    supporting: 1_024,
  },
  {
    id: 'u_3',
    username: 'tacticsboard',
    displayName: 'Tactics Board',
    bio: 'Breaking down the beautiful game, one Reel at a time.',
    country: 'England',
    countryFlag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    favoriteClub: 'Arsenal',
    verified: false,
    fans: 23_900,
    supporting: 356,
  },
  {
    id: 'u_4',
    username: 'goalkeeperdiaries',
    displayName: 'GK Diaries',
    bio: 'Saves, drills and keeper life. 🧤',
    country: 'Spain',
    countryFlag: '🇪🇸',
    favoriteClub: 'Real Madrid',
    verified: false,
    fans: 8_710,
    supporting: 190,
  },
];

export const reels: ReelRecord[] = [
  {
    id: 'r_1',
    userId: 'u_1',
    playbackUrl: 'https://stream.mux.com/v69RSHhFelSm4701snP22dYz2jICy4E4FUyk02rW4gxRM.m3u8',
    thumbnailUrl: poster('1'),
    caption: 'Rainbow flick into top bins. Who does it better? 🌈⚽',
    hashtags: ['skills', 'streetfootball', 'golazo'],
    durationSec: 24,
    status: 'published',
    cheers: 128_400,
    comments: 2_311,
    replays: 5_402,
    shares: 9_870,
    views: 1_920_000,
    createdAt: '2026-09-25T18:20:00Z',
  },
  {
    id: 'r_2',
    userId: 'u_2',
    playbackUrl: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/720/Big_Buck_Bunny_720_10s_2MB.mp4',
    thumbnailUrl: poster('2'),
    caption: 'Sunday league in Kano hits different. Tag your squad 👇',
    hashtags: ['naijafootball', 'grassroots', 'sundayleague'],
    durationSec: 10,
    status: 'published',
    cheers: 34_120,
    comments: 802,
    replays: 1_190,
    shares: 2_450,
    views: 310_000,
    createdAt: '2026-09-25T11:05:00Z',
  },
  {
    id: 'r_3',
    userId: 'u_3',
    playbackUrl: 'https://download.samplelib.com/mp4/sample-15s.mp4',
    thumbnailUrl: poster('3'),
    caption: 'Why the inverted full-back changes everything in build-up.',
    hashtags: ['tactics', 'premierleague', 'coaching'],
    durationSec: 15,
    status: 'published',
    cheers: 9_870,
    comments: 431,
    replays: 612,
    shares: 1_020,
    views: 88_400,
    createdAt: '2026-09-24T20:40:00Z',
  },
  {
    id: 'r_4',
    userId: 'u_4',
    playbackUrl: 'https://test-videos.co.uk/vids/jellyfish/mp4/h264/720/Jellyfish_720_10s_2MB.mp4',
    thumbnailUrl: poster('4'),
    caption: 'Reaction drill I do every session. Try it and tag me 🧤',
    hashtags: ['goalkeeper', 'training', 'skills'],
    durationSec: 10,
    status: 'published',
    cheers: 4_210,
    comments: 96,
    replays: 140,
    shares: 380,
    views: 41_000,
    createdAt: '2026-09-24T09:15:00Z',
  },
  {
    id: 'r_5',
    userId: 'u_1',
    playbackUrl: 'https://download.samplelib.com/mp4/sample-10s.mp4',
    thumbnailUrl: poster('5'),
    caption: 'Nutmeg challenge part 3. The last one is disrespectful 😂',
    hashtags: ['nutmeg', 'skills', 'golazo'],
    durationSec: 10,
    status: 'published',
    cheers: 76_900,
    comments: 1_540,
    replays: 3_300,
    shares: 6_120,
    views: 980_000,
    createdAt: '2026-09-23T16:00:00Z',
  },
  {
    id: 'r_6',
    userId: 'u_2',
    playbackUrl: 'https://test-videos.co.uk/vids/sintel/mp4/h264/720/Sintel_720_10s_2MB.mp4',
    thumbnailUrl: poster('6'),
    caption: 'Last-minute winner at the estate pitch. Scenes! 🇳🇬',
    hashtags: ['naijafootball', 'golazo', 'grassroots'],
    durationSec: 10,
    status: 'published',
    cheers: 51_300,
    comments: 1_202,
    replays: 2_010,
    shares: 3_870,
    views: 602_000,
    createdAt: '2026-09-22T19:30:00Z',
  },
  {
    id: 'r_7',
    userId: CURRENT_USER_ID,
    playbackUrl: 'https://download.samplelib.com/mp4/sample-20s.mp4',
    thumbnailUrl: poster('7'),
    caption: 'My first GamePulse Moment! Free kick practice 🎯',
    hashtags: ['freekick', 'training'],
    durationSec: 20,
    status: 'published',
    cheers: 37,
    comments: 4,
    replays: 1,
    shares: 2,
    views: 410,
    createdAt: '2026-09-21T15:10:00Z',
  },
];

export const hashtags: Hashtag[] = [
  { name: 'golazo', usageCount: 184_000, trendingScore: 98 },
  { name: 'skills', usageCount: 312_000, trendingScore: 95 },
  { name: 'naijafootball', usageCount: 64_500, trendingScore: 91 },
  { name: 'premierleague', usageCount: 420_000, trendingScore: 88 },
  { name: 'grassroots', usageCount: 22_900, trendingScore: 80 },
  { name: 'nutmeg', usageCount: 41_200, trendingScore: 77 },
  { name: 'tactics', usageCount: 18_300, trendingScore: 70 },
  { name: 'goalkeeper', usageCount: 15_100, trendingScore: 66 },
  { name: 'training', usageCount: 58_700, trendingScore: 61 },
  { name: 'freekick', usageCount: 12_400, trendingScore: 55 },
];

export const clubs = [
  'Arsenal',
  'Real Madrid',
  'Barcelona',
  'Enyimba',
  'Kano Pillars',
  'Flamengo',
  'Man City',
  'Al Nassr',
];

export const comments: CommentRecord[] = [
  { id: 'c_1', reelId: 'r_1', userId: 'u_2', text: 'This is filthy 🔥🔥', parentId: null, cheers: 342, createdAt: '2026-09-25T18:40:00Z' },
  { id: 'c_2', reelId: 'r_1', userId: 'u_3', text: 'Body shape before the flick is perfect.', parentId: null, cheers: 88, createdAt: '2026-09-25T19:02:00Z' },
  { id: 'c_3', reelId: 'r_1', userId: 'u_4', text: 'As a keeper I felt this one 😭', parentId: null, cheers: 51, createdAt: '2026-09-25T19:30:00Z' },
  { id: 'c_4', reelId: 'r_2', userId: 'u_1', text: 'Grassroots is where it starts 🙌', parentId: null, cheers: 120, createdAt: '2026-09-25T12:00:00Z' },
  { id: 'c_5', reelId: 'r_3', userId: 'u_2', text: 'Make a part 2 on pressing traps!', parentId: null, cheers: 19, createdAt: '2026-09-24T21:15:00Z' },
];

export const notifications: NotificationRecord[] = [
  { id: 'n_1', type: 'new_fan', actorId: 'u_1', reelId: null, text: 'became your Fan', read: false, createdAt: '2026-09-26T08:10:00Z' },
  { id: 'n_2', type: 'cheer', actorId: 'u_2', reelId: 'r_7', text: 'cheered your Moment', read: false, createdAt: '2026-09-26T07:45:00Z' },
  { id: 'n_3', type: 'comment', actorId: 'u_3', reelId: 'r_7', text: 'commented: "Great technique on that strike!"', read: false, createdAt: '2026-09-25T22:30:00Z' },
  { id: 'n_4', type: 'replay', actorId: 'u_4', reelId: 'r_7', text: 'replayed your Moment', read: true, createdAt: '2026-09-25T17:00:00Z' },
  { id: 'n_5', type: 'mention', actorId: 'u_2', reelId: 'r_6', text: 'mentioned you in a Moment', read: true, createdAt: '2026-09-24T13:20:00Z' },
  { id: 'n_6', type: 'system', actorId: null, reelId: null, text: 'Welcome to GamePulse! Support creators to shape your GameFeed.', read: true, createdAt: '2026-09-21T15:00:00Z' },
];
